const ADD_CONTACT = "ADD_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";
const SET_ALERT = "SET_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const LOADED_USER = "LOADED_USER";
const AUTH_FAIL = "AUTH_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

export {
  ADD_CONTACT,
  AUTH_FAIL,
  CLEAR_ALERT,
  DELETE_CONTACT,
  LOADED_USER,
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  REGISTER_FAIL,
  REGISTER_SUCCESS,
  SET_ALERT,
  UPDATE_CONTACT,
};
