const ADD_CONTACT = "ADD_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";
const FILTER_CONTACT = "FILTER_CONTACT";
const CLEAR_FILTER = "CLEAR_FILTER";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";

export {
  ADD_CONTACT,
  CLEAR_FILTER,
  DELETE_CONTACT,
  FILTER_CONTACT,
  REGISTER_FAIL,
  REGISTER_SUCCESS,
  REMOVE_ALERT,
  SET_ALERT,
  UPDATE_CONTACT,
};
